export const patientsData = [
  {
    id: 1234,
    img: 'assets/images/user-img.png',
    code: 'BD-425457',
    name: 'Mohamed Al Garhy',
    phone: '+96645454545',
    email: 'mohamed.algarhy@gmail.com',
    lastVisit: 'Urology',
    isAllSaved: true,
  },
  {
    id: 2345,
    img: 'assets/images/user-img.png',
    code: 'BD-3123',
    name: 'Ahmed Salam',
    phone: '+96612314',
    email: 'mohamed.algarhy@gmail.com',
    lastVisit: 'Urology',
    isAllSaved: false,
  },
  {
    id: 6343,
    img: 'assets/images/user-img.png',
    code: 'BD-4124',
    name: 'Esl',
    phone: '+966515125',
    email: 'mohamed.algarhy@gmail.com',
    lastVisit: 'Urology',
    isAllSaved: false,
  },
  {
    id: 5342,
    img: 'assets/images/user-img.png',
    code: 'BD-1251',
    name: 'Mohamed Al Garhy',
    phone: '+966152525',
    email: 'mohamed.algarhy@gmail.com',
    lastVisit: 'Urology',
    isAllSaved: true,
  },
  {
    id: 6432,
    img: 'assets/images/user-img.png',
    code: 'BD-555234',
    name: 'Mohamed Al Garhy',
    phone: '+966252525',
    email: 'mohamed.algarhy@gmail.com',
    lastVisit: 'Urology',
    isAllSaved: true,
  },
];
